name: uBOL-safari
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 9999
    steps:
      - name: uBOL-safari
        run: |
          wget -O uBOL-safari.zip https://github.com/CE1CECL/uBOL-home/releases/download/uBOLite_2025.814.1911-beta/uBOLite.beta.zip
          unzip -d uBOL-safari uBOL-safari.zip
          xcodebuild build -alltargets -project "./uBOL-safari/dist/safari/xcode/uBlock Origin Lite.xcodeproj"
          zip uBOL-safari.zip -9r uBOL-safari
      - name: Upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: uBOL-safari
          path: uBOL-safari.zip
